import { type Metadata } from "next";

import "~/styles/globals.css";

import React from "react";

import { TRPCReactProvider } from "../../trpc/react.jsx";

export const metadata: Metadata = {
  title: "@reliverse/cli",
  description: "Generated by @reliverse/cli",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
