export enum KeyVars {
  NEXT_PUBLIC_APP_URL = "NEXT_PUBLIC_APP_URL",
  DATABASE_URL = "DATABASE_URL",
  AUTH_SECRET = "AUTH_SECRET",
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
  CLERK_SECRET_KEY = "CLERK_SECRET_KEY",
  CLERK_ENCRYPTION_KEY = "CLERK_ENCRYPTION_KEY",
  UPLOADTHING_TOKEN = "UPLOADTHING_TOKEN",
  UPLOADTHING_SECRET = "UPLOADTHING_SECRET",
  RESEND_API_KEY = "RESEND_API_KEY",
  EMAIL_FROM_ADDRESS = "EMAIL_FROM_ADDRESS",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
  STRIPE_API_KEY = "STRIPE_API_KEY",
  STRIPE_WEBHOOK_SECRET = "STRIPE_WEBHOOK_SECRET",
  STRIPE_PRO_MONTHLY_PRICE_ID = "STRIPE_PRO_MONTHLY_PRICE_ID",
}

export type KeyType =
  | "string"
  | "email"
  | "password"
  | "number"
  | "boolean"
  | "database";

export type ServiceKey = {
  key: KeyVars;
  type?: KeyType;
  defaultValue?: string;
  instruction?: string;
  hidden?: boolean;
};
